#!/bin/sh

TARGET=www/css/style.css

echo "/* auto-generated by lessc, DO NOT EDIT MANUALLY, edit style.less instead and run ./compile-css.sh  */" >$TARGET
echo "" >>$TARGET
lessc www/css/style.less >>$TARGET
