<?php
$page = "languages";
$title = "LanguageTool";
$title2 = "Supported Languages";
$lastmod = "2013-06-30 21:31:00 CET";
$enable_tablesorter = 1;
include("../../include/header.php");
?>
		
<p class="firstpara">LanguageTool supports several languages to a different degree. This page lists the
number of rules per language to give a very rough indication of how well a
language is supported.</p>

<!-- Output of RuleOverview.java: -->

<b>Rules in LanguageTool 2.2</b><br />
Date: 2013-06-30<br /><br />

<table class="tablesorter sortable">
    <thead>
    <tr>
        <th valign='bottom' width="70">Language</th>
        <th valign='bottom' align="left" width="60">XML<br/>rules</th>
        <th width="120"></th>
        <th align="left" width="60">Java<br/>rules</th>
        <th align="left" width="60">False<br/>friends</th>
        <th valign='bottom' align="left">Rule Maintainers</th>
    </tr>
    </thead>
    <tbody>
    <tr><td valign="top">Asturian</td><td valign="top" align="right">61</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ast/src/main/resources/org/languagetool/rules/ast/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=ast">Browse</a></td><td valign="top" align="right">0</td><td valign="top" align="right">0</td><td valign="top" align="left">Xesús González Rato</td></tr>
    <tr><td valign="top">Belarusian</td><td valign="top" align="right">7</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/be/src/main/resources/org/languagetool/rules/be/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=be">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/be/src/main/java/org/languagetool/rules/be/">1</a></td><td valign="top" align="right">0</td><td valign="top" align="left">Alex Buloichik</td></tr>
    <tr><td valign="top"><a href="../br/">Breton</a></td><td valign="top" align="right">624</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/br/src/main/resources/org/languagetool/rules/br/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=br">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/br/src/main/java/org/languagetool/rules/br/">2</a></td><td valign="top" align="right">0</td><td valign="top" align="left"><a href="http://dominiko.livejournal.com/tag/lingvoilo">Dominique Pellé</a>, Fulup Jakez</td></tr>
    <tr><td valign="top"><a href="../ca/">Catalan</a></td><td valign="top" align="right">1355</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ca/src/main/resources/org/languagetool/rules/ca/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=ca">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ca/src/main/java/org/languagetool/rules/ca/">9</a></td><td valign="top" align="right">4</td><td valign="top" align="left">Ricard Roca, Jaume Ortolà</td></tr>
    <tr><td valign="top"><a href="../zh/">Chinese</a></td><td valign="top" align="right">786</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/zh/src/main/resources/org/languagetool/rules/zh/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=zh">Browse</a></td><td valign="top" align="right">0</td><td valign="top" align="right">0</td><td valign="top" align="left">Tao Lin, Fangjie Wang, Wenting Cheng, Xiang Yao, Tong Wang, Jiawen Mo, Jiarong Li, Weijie Huang, Yixin Zhou, Xinmin Chen, Xiaofei Liu, Debiao Luo</td></tr>
    <tr><td valign="top">Danish</td><td valign="top" align="right">78</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/da/src/main/resources/org/languagetool/rules/da/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=da">Browse</a></td><td valign="top" align="right">0</td><td valign="top" align="right">6</td><td valign="top" align="left">Esben Aaberg, Henrik Bendt</td></tr>
    <tr><td valign="top">Dutch</td><td valign="top" align="right">336</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=nl">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/nl/src/main/java/org/languagetool/rules/nl/">4</a></td><td valign="top" align="right">1</td><td valign="top" align="left"><a href="http://www.opentaal.org">OpenTaal</a></td></tr>
    <tr><td valign="top">English</td><td valign="top" align="right">912</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=en">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/">12</a></td><td valign="top" align="right">306</td><td valign="top" align="left"><a href="http://marcinmilkowski.pl">Marcin Miłkowski</a>, <a href="http://www.danielnaber.de">Daniel Naber</a></td></tr>
    <tr><td valign="top"><a href="../eo/">Esperanto</a></td><td valign="top" align="right">324</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/eo/src/main/resources/org/languagetool/rules/eo/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=eo">Browse</a></td><td valign="top" align="right">0</td><td valign="top" align="right">0</td><td valign="top" align="left"><a href="http://dominiko.livejournal.com/tag/lingvoilo">Dominique Pellé</a></td></tr>
    <tr><td valign="top"><a href="../fr/">French</a></td><td valign="top" align="right">2218</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=fr">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/">1</a></td><td valign="top" align="right">5</td><td valign="top" align="left">Agnes Souque, Hugo Voisard&nbsp;(2006-2007), <a href="http://dominiko.livejournal.com/tag/lingvoilo">Dominique Pellé</a></td></tr>
    <tr><td valign="top">Galician</td><td valign="top" align="right">153</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=gl">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/gl/src/main/java/org/languagetool/rules/gl/">2</a></td><td valign="top" align="right">113</td><td valign="top" align="left"><a href="http://www.linguarum.net/projects/languagetool-gl">Susana Sotelo Docío</a></td></tr>
    <tr><td valign="top"><a href="../de/">German</a></td><td valign="top" align="right">1801</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=de">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/">13</a></td><td valign="top" align="right">94</td><td valign="top" align="left">Jan Schreiber, Markus Brenneis, <a href="http://www.danielnaber.de">Daniel Naber</a></td></tr>
    <tr><td valign="top">Greek</td><td valign="top" align="right">16</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/el/src/main/resources/org/languagetool/rules/el/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=el">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/el/src/main/java/org/languagetool/rules/el/">2</a></td><td valign="top" align="right">0</td><td valign="top" align="left">Panagiotis Minos</td></tr>
    <tr><td valign="top">Icelandic</td><td valign="top" align="right">39</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/is/src/main/resources/org/languagetool/rules/is/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=is">Browse</a></td><td valign="top" align="right">0</td><td valign="top" align="right">0</td><td valign="top" align="left">Anton Karl Ingason</td></tr>
    <tr><td valign="top"><a href="../it/">Italian</a></td><td valign="top" align="right">132</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/it/src/main/resources/org/languagetool/rules/it/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=it">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/it/src/main/java/org/languagetool/rules/it/">2</a></td><td valign="top" align="right">36</td><td valign="top" align="left">Paolo Bianchini</td></tr>
    <tr><td valign="top">Japanese</td><td valign="top" align="right">21</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ja/src/main/resources/org/languagetool/rules/ja/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=ja">Browse</a></td><td valign="top" align="right">0</td><td valign="top" align="right">0</td><td valign="top" align="left">Takahiro Shinkai</td></tr>
    <tr><td valign="top">Khmer</td><td valign="top" align="right">31</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/km/src/main/resources/org/languagetool/rules/km/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=km">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/km/src/main/java/org/languagetool/rules/km/">5</a></td><td valign="top" align="right">0</td><td valign="top" align="left">Nathan Wells</td></tr>
    <tr><td valign="top">Lithuanian</td><td valign="top" align="right">4</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/lt/src/main/resources/org/languagetool/rules/lt/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=lt">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/lt/src/main/java/org/languagetool/rules/lt/">1</a></td><td valign="top" align="right">0</td><td valign="top" align="left">Mantas Kriaučiūnas</td></tr>
    <tr><td valign="top">Malayalam</td><td valign="top" align="right">18</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ml/src/main/resources/org/languagetool/rules/ml/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=ml">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ml/src/main/java/org/languagetool/rules/ml/">1</a></td><td valign="top" align="right">0</td><td valign="top" align="left">Jithesh.V.S</td></tr>
    <tr><td valign="top"><a href="../pl/">Polish</a></td><td valign="top" align="right">1036</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/pl/src/main/resources/org/languagetool/rules/pl/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=pl">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/pl/src/main/java/org/languagetool/rules/pl/">5</a></td><td valign="top" align="right">139</td><td valign="top" align="left">Marcin Miłkowski</td></tr>
    <tr><td valign="top"><a href="../pt/">Portuguese</a></td><td valign="top" align="right">104</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=pt">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/">1</a></td><td valign="top" align="right">0</td><td valign="top" align="left"><a href="http://www.marcoagpinto.com/">Marco A.G. Pinto</a></td></tr>
    <tr><td valign="top">Romanian</td><td valign="top" align="right">458</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ro/src/main/resources/org/languagetool/rules/ro/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=ro">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ro/src/main/java/org/languagetool/rules/ro/">4</a></td><td valign="top" align="right">0</td><td valign="top" align="left"><a href="http://www.archeus.ro">Ionuț Păduraru</a></td></tr>
    <tr><td valign="top"><a href="../ru/">Russian</a></td><td valign="top" align="right">217</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ru/src/main/resources/org/languagetool/rules/ru/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=ru">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/ru/src/main/java/org/languagetool/rules/ru/">5</a></td><td valign="top" align="right">1</td><td valign="top" align="left"><a href="http://myooo.ru/content/view/83/43/">Yakov Reztsov</a></td></tr>
    <tr><td valign="top">Slovak</td><td valign="top" align="right">55</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/sk/src/main/resources/org/languagetool/rules/sk/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=sk">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/sk/src/main/java/org/languagetool/rules/sk/">3</a></td><td valign="top" align="right">0</td><td valign="top" align="left"><a href="http://sk-spell.sk.cx">Zdenko Podobný</a></td></tr>
    <tr><td valign="top">Slovenian</td><td valign="top" align="right">85</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/sl/src/main/resources/org/languagetool/rules/sl/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=sl">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/sl/src/main/java/org/languagetool/rules/sl/">1</a></td><td valign="top" align="right">0</td><td valign="top" align="left">Martin Srebotnjak</td></tr>
    <tr><td valign="top">Spanish</td><td valign="top" align="right">103</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=es">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/es/src/main/java/org/languagetool/rules/es/">1</a></td><td valign="top" align="right">28</td><td valign="top" align="left"><a href="http://languagetool-es.blogspot.com/">Juan Martorell</a></td></tr>
    <tr><td valign="top">Swedish</td><td valign="top" align="right">26</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/sv/src/main/resources/org/languagetool/rules/sv/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=sv">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/sv/src/main/java/org/languagetool/rules/sv/">1</a></td><td valign="top" align="right">5</td><td valign="top" align="left">Niklas Johansson</td></tr>
    <tr><td valign="top">Tagalog</td><td valign="top" align="right">44</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/tl/src/main/resources/org/languagetool/rules/tl/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=tl">Browse</a></td><td valign="top" align="right">0</td><td valign="top" align="right">0</td><td valign="top" align="left"><a href="http://www.dlsu.edu.ph/research/centers/adric/nlp/">Nathaniel Oco</a>, <a href="http://www.dlsu.edu.ph/research/centers/adric/nlp/faculty/borra.asp">Allan Borra</a></td></tr>
    <tr><td valign="top">Ukrainian</td><td valign="top" align="right">137</td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/uk/src/main/resources/org/languagetool/rules/uk/grammar.xml?content-type=text%2Fplain">XML</a> / <a href="http://community.languagetool.org/rule/list?lang=uk">Browse</a></td><td valign="top" align="right"><a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-language-modules/uk/src/main/java/org/languagetool/rules/uk/">4</a></td><td valign="top" align="right">0</td><td valign="top" align="left">Andriy Rysin, Maksym Davydov</td></tr>
    </tbody>
</table>

<!-- End Output of RuleOverview.java -->

<p>The number of Java rules listed is only the number of rules specific
to that language. There are some rules that deal with punctuation
and that apply to almost all languages.</p>

<p>
<a href="http://svn.code.sf.net/p/languagetool/code/trunk/languagetool/languagetool-core/src/main/resources/org/languagetool/rules/false-friends.xml">Show false friend rules</a>
</p>
        
<!--
<p>Auto-detected means that a language can be detected by LanguageTool without the user needing to select the language.</p>
-->

<?php
include("../../include/footer.php");
?>
